routes/web.php
<?php

use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\UserController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes(); 

Route::group(['middleware' => ['auth', 'xss']], function () {
    Route::resource('profile', '\App\Http\Controllers\ProfileController');
    Route::resource('users', '\App\Http\Controllers\UserController');
    Route::resource('employees', '\App\Http\Controllers\EmployeeController');

    Route::resource('permission', '\App\Http\Controllers\PermissionController');
    Route::resource('roles', '\App\Http\Controllers\RoleController');
    Route::resource('module', '\App\Http\Controllers\ModuleController');
    Route::resource('forms', '\App\Http\Controllers\FormController');
    Route::resource('formvalues', '\App\Http\Controllers\FormValueController');

});

Route::get('/', [HomeController::class, 'index'])->name('home')->middleware(['auth', 'xss']);
Route::post('/chart', [HomeController::class, 'formchart'])->name('get.chart.data')->middleware(['auth', 'xss',]);


Route::get('/invisible', function () {
    return view('invisible');
});
Route::post('/invisible', function (Request $request) {
    $request->validate([
        'g-recaptcha-response' => 'required|captcha'
    ]);

    return 'Data is valid';
});

Route::get('/form-values/{id}/download/pdf',['as' => 'download.form.values.pdf','uses' =>'\App\Http\Controllers\FormValueController@download_pdf'])->middleware(['auth','xss']);

Route::get('update-avatar/{id}', [
    'as' => 'update-avatar',
    'uses' => '\App\Http\Controllers\ProfileController@showAvatar'
])->middleware(['auth', 'xss']);

Route::get('design/{id}', [
    'as' => 'forms.design',
    'uses' => '\App\Http\Controllers\FormController@design'
])->middleware(['auth', 'xss']);
Route::put('/forms/design/{id}', ['as' => 'forms.design.update', 'uses' => '\App\Http\Controllers\FormController@designUpdate'])->middleware(['auth', 'xss']);

Route::post('update-avatar/{id}', '\App\Http\Controllers\ProfileController@updateAvatar');

Route::post('update-profile-login/{id}', [
    'uses' => '\App\Http\Controllers\ProfileController@updateLogin',
    'as' => 'update-login',
]);

Route::get('/forms/fill/{id}', ['as' => 'forms.fill', 'uses' => '\App\Http\Controllers\FormController@fill'])->middleware(['auth', 'xss']);
Route::get('/forms/survey/{id}', ['as' => 'forms.survey', 'uses' => '\App\Http\Controllers\FormController@publicFill']);
Route::put('/forms/fill/{id}', ['as' => 'forms.fill.store', 'uses' => '\App\Http\Controllers\FormController@fillStore']);
Route::get('/form-values/{id}/edit', ['as' => 'edit.form.values', 'uses' => '\App\Http\Controllers\FormValueController@edit'])->middleware(['auth', 'xss']);
Route::get('/form-values/{id}/view', ['as' => 'view.form.values', 'uses' => '\App\Http\Controllers\FormValueController@showSubmitedForms'])->middleware(['auth', 'xss']);
Route::post('/mass/export',['as' => 'mass.export','uses' =>'\App\Http\Controllers\FormValueController@export'])->middleware(['auth','xss']);
Route::post('/form-duplicate',['as' => 'forms.duplicate','uses' =>'\App\Http\Controllers\FormController@duplicate'])->middleware(['auth','xss']);



Route::resource('role', '\App\Http\Controllers\RoleController');
Route::post('/role-permission/{id}', [
    'as' => 'roles_permit',
    'uses' => '\App\Http\Controllers\RoleController@assignPermission',
]);

Route::get('/settings', [SettingsController::class, 'index'])->name('settings')->middleware(['auth', 'xss']);

Route::post('settings/app-name/update', [
    'as' => 'settings/app-name/update',
    'uses' => '\App\Http\Controllers\SettingsController@appNameUpdate',
])->middleware(['auth', 'xss']);
Route::post('settings/app-logo/update', [
    'as' => 'settings/app-logo/update',
    'uses' => '\App\Http\Controllers\SettingsController@appLogoUpdate',
])->middleware(['auth', 'xss']);

Route::post('settings/pusher-setting/update', [
    'as' => 'settings/pusher-setting/update',
    'uses' => '\App\Http\Controllers\SettingsController@pusherSettingUpdate',
])->middleware(['auth', 'xss']);

Route::post('settings/wasabi-setting/update', [
    'as' => 'settings/wasabi-setting/update',
    'uses' => '\App\Http\Controllers\SettingsController@wasabiSettingUpdate',
])->middleware(['auth', 'xss']);
Route::post('settings/captcha-setting/update', [
    'as' => 'settings/captcha-setting/update',
    'uses' => '\App\Http\Controllers\SettingsController@captchaSettingUpdate',
])->middleware(['auth', 'xss']);

Route::post('settings/email-setting/update', [
    'as' => 'settings/email-setting/update',
    'uses' => '\App\Http\Controllers\SettingsController@emailSettingUpdate',
])->middleware(['auth', 'xss']);

Route::post('settings/auth-settings/update', [
    'as' => 'settings/auth-settings/update',
    'uses' => '\App\Http\Controllers\SettingsController@authSettingsUpdate',
])->middleware(['auth', 'xss']);

Route::post('test-mail', '\App\Http\Controllers\SettingsController@testSendMail')->name('test.send.mail')->middleware(['auth', 'xss']);
Route::post('/verify-2fa', [
    'as' => 'verify-2fa',
    'uses' => '\App\Http\Controllers\ProfileController@verify'
]);

Route::post('/activate-2fa', [
    'uses' => '\App\Http\Controllers\ProfileController@activate',
    'as' => 'activate-2fa'
]);

Route::post('/enable-2fa', [
    'uses' => '\App\Http\Controllers\ProfileController@enable',
    'as' => 'enable-2fa'
]);

Route::post('/disable-2fa', [
    'uses' => '\App\Http\Controllers\ProfileController@disable',
    'as' => 'disable-2fa'
]);

Route::get('/2fa/instruction', [
    'uses' => '\App\Http\Controllers\ProfileController@instruction',
]);

Route::post('/2fa', function () {
    return redirect(URL()->previous());
})->name('2fa')->middleware('2fa');

Route::group(['prefix' => '2fa'], function () {
    Route::get('/', '\App\Http\Controllers\LoginSecurityController@show2faForm');
    Route::post('/generateSecret', '\App\Http\Controllers\LoginSecurityController@generate2faSecret')->name('generate2faSecret');
    Route::post('/enable2fa', '\App\Http\Controllers\LoginSecurityController@enable2fa')->name('enable2fa');
    Route::post('/disable2fa', '\App\Http\Controllers\LoginSecurityController@disable2fa')->name('disable2fa');

    Route::post('/2faVerify', function () {
        return redirect(URL()->previous());
    })->name('2faVerify')->middleware('2fa');
});

Route::get('/test_middleware', function () {
    return "2FA middleware work!";
})->middleware(['auth', '2fa']);

Route::any('(:any)/(:all?)', function ($first, $rest = '') {
    $page = $rest ? "{$first}/{$rest}" : $first;
    dd($page);
});

Route::get('setting/{id}', [
    'as' => 'setting',
    'uses' => '\App\Http\Controllers\SettingsController@loadsetting'
])->middleware(['auth', 'xss']);

Route::post('ckeditor/upload', '\App\Http\Controllers\FormController@upload')->name('ckeditor.upload');
Route::group(
    ['middleware' => ['auth', 'xss']],
    function () {
        Route::get('change-language/{lang}', '\App\Http\Controllers\LanguageController@changeLanquage')->name('change.language');
        Route::get('manage-language/{lang}', '\App\Http\Controllers\LanguageController@manageLanguage')->name('manage.language');
        Route::post('store-language-data/{lang}', '\App\Http\Controllers\LanguageController@storeLanguageData')->name('store.language.data');
        Route::get('create-language', '\App\Http\Controllers\LanguageController@createLanguage')->name('create.language');
        Route::post('store-language', '\App\Http\Controllers\LanguageController@storeLanguage')->name('store.language');
        Route::delete('/lang/{lang}', '\App\Http\Controllers\LanguageController@destroyLang')->name('lang.destroy');
    }
);

/*
|--------------------------------------------------------------------------
| karthik test Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

app/Http/Controllers/FormValueController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\FormValuesDataTable;
use App\Models\Form;
use App\Models\FormValue;
use App\Models\UserForm;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;

class FormValueController extends Controller
{

    public function index(FormValuesDataTable $dataTable)
    {
        if (\Auth::user()->can('manage-submitted-form')) {
            $forms = Form::all();
            return $dataTable->render('form_value.index', compact('forms'));
        } else {
            return redirect()->back()->with('error', __('Permission Denied.'));
        }
    }

    public function showSubmitedForms($form_id, FormValuesDataTable $dataTable)
    {
        if (\Auth::user()->can('manage-submitted-form')) {
            $forms = Form::all();
            $forms_details = Form::find($form_id);
            return $dataTable->render('form_value.view_submited_form', compact('forms', 'forms_details'));
        } else {
            return redirect()->back()->with('error', __('Permission Denied.'));
        }
    }

    public function show($id)
    {
        if (\Auth::user()->can('show-submitted-form')) {
            $form_value = FormValue::find($id);
            $array = json_decode($form_value->json);
            return view('form_value.view', compact('form_value', 'array'));
        } else {
            return redirect()->back()->with('error', __('Permission Denied.'));
        }
    }

    public function edit($id)
    {
        $usr = \Auth::user();
        $user_role = $usr->roles->first()->id;
        $form_value = FormValue::find($id);
        $formallowededit = UserForm::where('role_id', $user_role)->where('form_id', $form_value->form_id)->count();
        if (\Auth::user()->can('edit-form') && $usr->type == 'Admin') {


            $array = json_decode($form_value->json);
            $form = $form_value->Form;
            $frm = Form::find($form_value->form_id);
            return view('form.fill', compact('form', 'form_value', 'array'));
        } else {
            if (\Auth::user()->can('edit-form') && $formallowededit > 0) {
                $form_value = FormValue::find($id);
                $array = json_decode($form_value->json);
                $form = $form_value->Form;
                $frm = Form::find($form_value->form_id);
                return view('form.fill', compact('form', 'form_value', 'array'));
            } else {
                return redirect()->back()->with('error', __('Permission Denied.'));
            }
        }
    }

    public function destroy($id)
    {
        if (\Auth::user()->can('delete-submitted-form')) {
            FormValue::find($id)->delete();
            return redirect()->back()->with('success',  __('Form successfully deleted!'));
        } else {
            return redirect()->back()->with('error', __('Permission Denied.'));
        }
    }

    public function download_pdf($id)
    {
        $form_value = FormValue::where('id', 'REGEXP', '[[:<:]]' . $id . '[[:>:]]')->first();
        if ($form_value) {
            $form_value->createPDF();
        } else {
            $form_value = FormValue::where('id', '=', $id)->first();
            if (!$form_value) {

                $id = Crypt::decryptString($id);
                $form_value = FormValue::find($id);
            }
            if ($form_value) {
                $form_value->createPDF();
            } else {
                return redirect()->route('home')->with('error', __('File is not exist.'));
            }
        }
    }


    public function export(Request $request)
    {

        // dd($request->all());
        $form_values = FormValue::where('form_id', $request->form_id);
        if ($request->start_date && $request->end_date) {
            $form_values->whereBetween('form_values.created_at', [$request->start_date, $request->end_date]);
        }
        $form_values = $form_values->get();
        // dd($form_values);
        // $form_values = FormValue::whereIn('id',$ids)->get();
        foreach ($form_values as $form_value) {
            $ids[] = $form_value->id;
        }

        // $ids = json_decode($ids);
        if ($ids) {
            $form_values = FormValue::whereIn('id', $ids)->get();
            if ($form_values) {

                $file_path = 'app/public/csv/Temp_' . time() . '.csv';
                $file = fopen(storage_path($file_path), 'w');

                foreach ($form_values as $key => $form_value) {

                    $ValuForm_array = json_decode($form_value->json);

                    $csv_label = [];
                    $csv_value = [];


                    $skip = 0;
                    foreach ($ValuForm_array as $data) {
                        if ($skip) {
                            $skip--;
                            continue;
                        }
                        if (isset($data->value) || isset($data->values)) {

                            if ($data->type == "starRating") {
                                $csv_label[] = $data->label;
                                $csv_value[] = $data->value;
                            } else if (isset($data->values)) {

                                $value = '';
                                foreach ($data->values as $sub_data) {

                                    if ($data->type == "checkbox-group") {
                                        if (isset($sub_data->selected)) {
                                            $value .= $sub_data->label . ', ';
                                        }
                                    } else if ($data->type == "radio-group") {
                                        if (isset($sub_data->selected)) {
                                            $value .= $sub_data->label . ', ';
                                        }
                                    } else {
                                        if (isset($sub_data->selected)) {
                                            $value .= $sub_data->label . ', ';
                                        }
                                    }
                                }
                                $value = rtrim($value, ', ');
                                $csv_label[] = $data->label;
                                $csv_value[] = $value;
                            } else {
                                if ($data->type == "file") {
                                } else {
                                    if (isset($data->subtype) && $data->subtype == 'signature') {
                                    } else {
                                        $csv_label[] = $data->label;
                                        $csv_value[] = $data->value;
                                    }
                                }
                            }
                        } else if ($data->type == "header") {
                            if (isset($data->selected) && $data->selected) {
                                $skip = intval($data->number_of_control);
                                $csv_label[] = $data->label;
                                $csv_value[] = 'N/A';
                            } else {
                                $csv_label[] = $data->label;
                                $csv_value[] = '';
                            }
                        } else {
                            if (isset($data->label)) {

                                $csv_label[] = ($data->label) ? $data->label : '';
                                $csv_value[] = '';
                            }
                        }
                    }

                    if ($key == 0) {
                        fputcsv($file, $csv_label);
                    }
                    fputcsv($file, $csv_value);
                }
                // dd($file_path,$form_value->Form->title ,$file);
                fclose($file);
                $headers = array(
                    'Content-Type: text/csv',
                  );

                return response()->download(storage_path($file_path), $form_value->Form->title . '_' . ".csv",$headers);
            } else {
                return redirect()->back()->with('error', __('Permission Denied.'));
            }
        } else {
            return redirect()->back()->with('error', __('Permission Denied.'));
        }
    }
}

resources/views/form_value/action.blade.php
@can('edit-submitted-form')
    <a href="{{ route('formvalues.edit', $formValue->id) }}" target="_blank" title="{{ __('Edit Survey') }}"
        class="btn btn-info mr-1" data-toggle="tooltip" data-original-title="{{ __('Edit') }}"><i
            class="fas fa-edit mr-0"></i> </a>
@endcan

@can('show-submitted-form')
    <a href="{{ route('formvalues.show', $formValue->id) }}" title="{{ __('View Survey') }}"
        class="btn btn-primary  mr-1" data-toggle="tooltip" data-original-title="{{ __('View') }}"><i
            class="fas fa-eye mr-0"></i> </span></a>
@endcan

@can('download-submitted-form')
    <a href="{{ route('download.form.values.pdf', $formValue->id) }}" title="{{ __('Download PDF') }}"
        class="btn btn-success  mr-1" data-toggle="tooltip" data-original-title="{{ __('Download') }}"><i
            class="fas fa-file-download mr-0"></i></a>
@endcan

@can('delete-submitted-form')
    <a href="#" class="btn btn-danger delete-action" data-form-id="delete-form-{{ $formValue->id }}"><i
            class="fas fa-trash mr-0"></i> </a>
    {!! Form::open(['method' => 'DELETE', 'route' => ['formvalues.destroy', $formValue->id], 'id' => 'delete-form-' . $formValue->id]) !!}
    {!! Form::close() !!}
@endcan

resources/views/form_value/index.blade.php
@extends('layouts.main')
@section('title', 'Submitted Forms')
@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>{{ __('Submitted Forms') }}</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="{{ route('home') }}">{{ __('Dashboard') }}</a></div>
                    <div class="breadcrumb-item">{{ __('Submitted Forms') }}</div>
                </div>
            </div>
            <div class="section-body filter">
                <div class="row">
                    <div class="col-lg-6  custom_left"></div>
                    <div class="col-lg-6  custom_right">
                        @can('manage-submitted-form')
                            {{-- <select class="form-control custom_select text-left form-control-sm  w-auto d-inline" name="form"
                                id="form">
                                <option value="">{{ __('All Forms') }}</option>
                                @foreach ($forms as $form)
                                    <option value="{{ $form->id }}">{{ $form->title }}</option>
                                @endforeach
                            </select> --}}
                            <input type="text"
                                class="form-control form-control-sm w-auto d-inline custom_padding form-control-light"
                                id="duration1" name="duration" value="{{ __('Select Date Range') }}" />
                            <input type="hidden" name="start_date1" id="start_date1" />
                            <input type="hidden" name="due_date1" id="end_date1" />
                            <button class="btn btn-primary btn-lg ml-2" id="filter">{{ __('Filter') }}</button>
                        @endcan
                    </div>
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="table-responsive py-4">
                                            {{ $dataTable->table(['width' => '100%']) }}
                                            {!! Form::open(['route' => ['mass.export'], 'method' => 'post','id'=>'mass_export']) !!}
                                            {{ Form::hidden('ids') }}
                                        {!! Form::close() !!}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection
@push('style')
    <link rel="stylesheet" type="text/css" href="{{ asset('vendor/daterangepicker/daterangepicker.css') }}" />
    <link rel="stylesheet" href="{{ asset('vendor/select2/dist/css/select2.min.css') }}">
    @include('layouts.includes.datatable_css')
@endpush
@push('script')
    <script type="text/javascript" src="{{ asset('vendor/daterangepicker/daterangepicker.min.js') }}"></script>
    <script src="{{ asset('vendor/select2/dist/js/select2.full.min.js') }}"></script>
    @include('layouts.includes.datatable_js')
    <script>
        $(document).ready(function() {
            $('.custom_select').select2();
            $(document).on("click", "#filter", function() {
                getData();
            });
            window.LaravelDataTables = null;

            function getData() {
                if (window.LaravelDataTables == null) {
                    window.LaravelDataTables = $("#forms-table").DataTable({
                        "serverSide": true,
                        "processing": true,
                        "ajax": {
                            "url": "{{ route('formvalues.index') }}",
                            "type": "GET",
                            "data": function(data) {
                                for (var i = 0, len = data.columns.length; i < len; i++) {
                                    if (!data.columns[i].search.value) delete data.columns[i].search;
                                    if (data.columns[i].searchable === true) delete data.columns[i]
                                        .searchable;
                                    if (data.columns[i].orderable === true) delete data.columns[i]
                                        .orderable;
                                    if (data.columns[i].data === data.columns[i].name) delete data
                                        .columns[i]
                                        .name;
                                }
                                delete data.search.regex;
                                data.form = $("#form").val();
                                data.start_date = $("#start_date1").val();
                                data.end_date = $("#end_date1").val();
                            }
                        },
                        "columns": [{
                            "name": "id",
                            "data": "DT_RowIndex",
                            "title": "No",
                            "orderable": true,
                            "searchable": true
                        }, {
                            "data": "title",
                            "name": "forms.title",
                            "title": "Title",
                            "orderable": true,
                            "searchable": true
                        }, {
                            "data": "user",
                            "name": "user",
                            "title": "User",
                            "orderable": true,
                            "searchable": true
                        }, {
                            "data": "created_at",
                            "name": "created_at",
                            "title": "Created At",
                            "orderable": true,
                            "searchable": true
                        }, {
                            "data": "action",
                            "name": "action",
                            "title": "Action",
                            "orderable": false,
                            "searchable": false,
                            "className": "text-right"
                        }],
                        "dom": "Bfrtip",
                        "order": [
                            [3, "desc"]
                        ],
                        "language": {
                            "paginate": {
                                "next": "<i class=\"fas fa-angle-right\"><\/i>",
                                "previous": "<i class=\"fas fa-angle-left\"><\/i>"
                            }
                        },
                        "language": {
                            "buttons": {
                                "export": "{{ __('Export') }}",
                                "print": "{{ __('Print') }}",
                                "reset": "{{ __('Reset') }}",
                                "reload": "{{ __('Reload') }}",
                                "excel": "{{ __('Excel') }}",
                                "csv": "{{ __('CSV') }}",
                                "pageLength": "{{ __('Show %d rows') }}"
                            }
                        },
                        "dom": "\n<'row'<'col-sm-12'><'col-sm-9 'B><'col-sm-3'f>>\n<'row'<'col-sm-12'tr>>\n<'row mt-3'<'col-sm-5'i><'col-sm-7'p>>\n",
                        "buttons": [{
                            "extend": "export",
                            "className": "btn btn-primary btn-sm no-corner"
                        }, {
                            "extend": "print",
                            "className": "btn btn-primary btn-sm no-corner"
                        }, {
                            "extend": "reset",
                            "className": "btn btn-primary btn-sm no-corner"
                        }, {
                            "extend": "reload",
                            "className": "btn btn-primary btn-sm no-corner"
                        }, {
                            "extend": "pageLength",
                            "className": "btn btn-danger btn-sm no-corner"
                        }],
                        "scrollX": true
                    })
                    ->language([
                'buttons'=>[
                    'create'=>__('Create'),
                    'export'=>__('Export'),
                    'print'=>__('Print'),
                    'reset'=>__('Reset'),
                    'reload'=>__('Reload'),
                    'excel'=>__('Excel'),
                    'csv'=>__('CSV'),
                    'pageLength'=>__('Show %d rows'),
                ]
            ]);
                } else {
                    window.LaravelDataTables.ajax.reload();
                }
            }
            getData();
            $(function() {
                function cb(start, end) {
                    $("#duration1").val(start.format('MMM D, YY hh:mm A') + ' - ' + end.format(
                        'MMM D, YY hh:mm A'));
                    $('input[name="start_date1"]').val(start.format('YYYY-MM-DD HH:mm:ss'));
                    $('input[name="due_date1"]').val(end.format('YYYY-MM-DD HH:mm:ss'));
                }
                $('#duration1').daterangepicker({
                    timePicker: true,
                    autoUpdateInput: false,
                    locale: {
                        format: 'MMM D, YY hh:mm A',
                        applyLabel: "{{ __('Apply') }}",
                        cancelLabel: "{{ __('Cancel') }}",
                        fromLabel: "{{ __('From') }}",
                        toLabel: "{{ __('To') }}",
                        daysOfWeek: [
                            "{{ __('Sun') }}",
                            "{{ __('Mon') }}",
                            "{{ __('Tue') }}",
                            "{{ __('Wed') }}",
                            "{{ __('Thu') }}",
                            "{{ __('Fri') }}",
                            "{{ __('Sat') }}"
                        ],
                        monthNames: [
                            "{{ __('January') }}",
                            "{{ __('February') }}",
                            "{{ __('March') }}",
                            "{{ __('April') }}",
                            "{{ __('May') }}",
                            "{{ __('June') }}",
                            "{{ __('July') }}",
                            "{{ __('August') }}",
                            "{{ __('September') }}",
                            "{{ __('October') }}",
                            "{{ __('November') }}",
                            "{{ __('December') }}"
                        ],
                    }
                }, cb);
            });
        });
    </script>
@endpush

resources/views/form_value/public_view.blade.php
@extends('layouts.form')
@section('title', '')
@section('content')
    <div class="main-content p-0">
        <section class="section">
            @include('form.form')
        </section>
    </div>
@endsection
@push('style')

    <link href="{{ asset('assets/jqueryform/css/jquery.rateyo.min.css') }}" rel="stylesheet" />
    <link rel="stylesheet" href="{{ asset('vendor/select2/dist/css/select2.min.css') }}">
@endpush
@push('script')
    <script src="{{ asset('assets/jqueryform/js/jquery.rateyo.min.js') }}"></script>
    <script src="{{ asset('vendor/select2/dist/js/select2.full.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            setTimeout(function() {
                $("#setData").trigger('click');
            }, 30);
        });
    </script>
    <script>
        $('.custom_select').select2();
        var $starRating = $('.starRating');
        if ($starRating.length) {
            $starRating.each(function() {
                var val = $(this).attr('data-value');
                var num_of_star = $(this).attr('data-num_of_star');
                $(this).rateYo({
                    rating: val,
                    halfStar: true,
                    numStars: num_of_star,
                    precision: 2,
                    onSet: function(rating, rateYoInstance) {
                        num_of_star = $(rateYoInstance.node).attr('data-num_of_star');
                        var input = ($(rateYoInstance.node).attr('id'));
                        if (num_of_star == 10) {
                            rating = rating * 2;
                        }
                        $('input[name="' + input + '"]').val(rating);
                        calculate_total($('input[name="' + input + '"]').attr('data-group'));
                    }
                })
            });
        }
    </script>
@endpush