routes/web.php
<?php

use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\UserController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes(); 

Route::group(['middleware' => ['auth', 'xss']], function () {
    Route::resource('profile', '\App\Http\Controllers\ProfileController');
    Route::resource('users', '\App\Http\Controllers\UserController');
    Route::resource('employees', '\App\Http\Controllers\EmployeeController');

    Route::resource('permission', '\App\Http\Controllers\PermissionController');
    Route::resource('roles', '\App\Http\Controllers\RoleController');
    Route::resource('module', '\App\Http\Controllers\ModuleController');
    Route::resource('forms', '\App\Http\Controllers\FormController');
    Route::resource('formvalues', '\App\Http\Controllers\FormValueController');

});

Route::get('/', [HomeController::class, 'index'])->name('home')->middleware(['auth', 'xss']);
Route::post('/chart', [HomeController::class, 'formchart'])->name('get.chart.data')->middleware(['auth', 'xss',]);


Route::get('/invisible', function () {
    return view('invisible');
});
Route::post('/invisible', function (Request $request) {
    $request->validate([
        'g-recaptcha-response' => 'required|captcha'
    ]);

    return 'Data is valid';
});

Route::get('/form-values/{id}/download/pdf',['as' => 'download.form.values.pdf','uses' =>'\App\Http\Controllers\FormValueController@download_pdf'])->middleware(['auth','xss']);

Route::get('update-avatar/{id}', [
    'as' => 'update-avatar',
    'uses' => '\App\Http\Controllers\ProfileController@showAvatar'
])->middleware(['auth', 'xss']);

Route::get('design/{id}', [
    'as' => 'forms.design',
    'uses' => '\App\Http\Controllers\FormController@design'
])->middleware(['auth', 'xss']);
Route::put('/forms/design/{id}', ['as' => 'forms.design.update', 'uses' => '\App\Http\Controllers\FormController@designUpdate'])->middleware(['auth', 'xss']);

Route::post('update-avatar/{id}', '\App\Http\Controllers\ProfileController@updateAvatar');

Route::post('update-profile-login/{id}', [
    'uses' => '\App\Http\Controllers\ProfileController@updateLogin',
    'as' => 'update-login',
]);

Route::get('/forms/fill/{id}', ['as' => 'forms.fill', 'uses' => '\App\Http\Controllers\FormController@fill'])->middleware(['auth', 'xss']);
Route::get('/forms/survey/{id}', ['as' => 'forms.survey', 'uses' => '\App\Http\Controllers\FormController@publicFill']);
Route::put('/forms/fill/{id}', ['as' => 'forms.fill.store', 'uses' => '\App\Http\Controllers\FormController@fillStore']);
Route::get('/form-values/{id}/edit', ['as' => 'edit.form.values', 'uses' => '\App\Http\Controllers\FormValueController@edit'])->middleware(['auth', 'xss']);
Route::get('/form-values/{id}/view', ['as' => 'view.form.values', 'uses' => '\App\Http\Controllers\FormValueController@showSubmitedForms'])->middleware(['auth', 'xss']);
Route::post('/mass/export',['as' => 'mass.export','uses' =>'\App\Http\Controllers\FormValueController@export'])->middleware(['auth','xss']);
Route::post('/form-duplicate',['as' => 'forms.duplicate','uses' =>'\App\Http\Controllers\FormController@duplicate'])->middleware(['auth','xss']);



Route::resource('role', '\App\Http\Controllers\RoleController');
Route::post('/role-permission/{id}', [
    'as' => 'roles_permit',
    'uses' => '\App\Http\Controllers\RoleController@assignPermission',
]);

Route::get('/settings', [SettingsController::class, 'index'])->name('settings')->middleware(['auth', 'xss']);

Route::post('settings/app-name/update', [
    'as' => 'settings/app-name/update',
    'uses' => '\App\Http\Controllers\SettingsController@appNameUpdate',
])->middleware(['auth', 'xss']);
Route::post('settings/app-logo/update', [
    'as' => 'settings/app-logo/update',
    'uses' => '\App\Http\Controllers\SettingsController@appLogoUpdate',
])->middleware(['auth', 'xss']);

Route::post('settings/pusher-setting/update', [
    'as' => 'settings/pusher-setting/update',
    'uses' => '\App\Http\Controllers\SettingsController@pusherSettingUpdate',
])->middleware(['auth', 'xss']);

Route::post('settings/wasabi-setting/update', [
    'as' => 'settings/wasabi-setting/update',
    'uses' => '\App\Http\Controllers\SettingsController@wasabiSettingUpdate',
])->middleware(['auth', 'xss']);
Route::post('settings/captcha-setting/update', [
    'as' => 'settings/captcha-setting/update',
    'uses' => '\App\Http\Controllers\SettingsController@captchaSettingUpdate',
])->middleware(['auth', 'xss']);

Route::post('settings/email-setting/update', [
    'as' => 'settings/email-setting/update',
    'uses' => '\App\Http\Controllers\SettingsController@emailSettingUpdate',
])->middleware(['auth', 'xss']);

Route::post('settings/auth-settings/update', [
    'as' => 'settings/auth-settings/update',
    'uses' => '\App\Http\Controllers\SettingsController@authSettingsUpdate',
])->middleware(['auth', 'xss']);

Route::post('test-mail', '\App\Http\Controllers\SettingsController@testSendMail')->name('test.send.mail')->middleware(['auth', 'xss']);
Route::post('/verify-2fa', [
    'as' => 'verify-2fa',
    'uses' => '\App\Http\Controllers\ProfileController@verify'
]);

Route::post('/activate-2fa', [
    'uses' => '\App\Http\Controllers\ProfileController@activate',
    'as' => 'activate-2fa'
]);

Route::post('/enable-2fa', [
    'uses' => '\App\Http\Controllers\ProfileController@enable',
    'as' => 'enable-2fa'
]);

Route::post('/disable-2fa', [
    'uses' => '\App\Http\Controllers\ProfileController@disable',
    'as' => 'disable-2fa'
]);

Route::get('/2fa/instruction', [
    'uses' => '\App\Http\Controllers\ProfileController@instruction',
]);

Route::post('/2fa', function () {
    return redirect(URL()->previous());
})->name('2fa')->middleware('2fa');

Route::group(['prefix' => '2fa'], function () {
    Route::get('/', '\App\Http\Controllers\LoginSecurityController@show2faForm');
    Route::post('/generateSecret', '\App\Http\Controllers\LoginSecurityController@generate2faSecret')->name('generate2faSecret');
    Route::post('/enable2fa', '\App\Http\Controllers\LoginSecurityController@enable2fa')->name('enable2fa');
    Route::post('/disable2fa', '\App\Http\Controllers\LoginSecurityController@disable2fa')->name('disable2fa');

    Route::post('/2faVerify', function () {
        return redirect(URL()->previous());
    })->name('2faVerify')->middleware('2fa');
});

Route::get('/test_middleware', function () {
    return "2FA middleware work!";
})->middleware(['auth', '2fa']);

Route::any('(:any)/(:all?)', function ($first, $rest = '') {
    $page = $rest ? "{$first}/{$rest}" : $first;
    dd($page);
});

Route::get('setting/{id}', [
    'as' => 'setting',
    'uses' => '\App\Http\Controllers\SettingsController@loadsetting'
])->middleware(['auth', 'xss']);

Route::post('ckeditor/upload', '\App\Http\Controllers\FormController@upload')->name('ckeditor.upload');
Route::group(
    ['middleware' => ['auth', 'xss']],
    function () {
        Route::get('change-language/{lang}', '\App\Http\Controllers\LanguageController@changeLanquage')->name('change.language');
        Route::get('manage-language/{lang}', '\App\Http\Controllers\LanguageController@manageLanguage')->name('manage.language');
        Route::post('store-language-data/{lang}', '\App\Http\Controllers\LanguageController@storeLanguageData')->name('store.language.data');
        Route::get('create-language', '\App\Http\Controllers\LanguageController@createLanguage')->name('create.language');
        Route::post('store-language', '\App\Http\Controllers\LanguageController@storeLanguage')->name('store.language');
        Route::delete('/lang/{lang}', '\App\Http\Controllers\LanguageController@destroyLang')->name('lang.destroy');
    }
);

/*
|--------------------------------------------------------------------------
| karthik test Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="{{setting('rtl') == '1'?'rtl':''}}">

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>@yield('title')  </title>
    <link rel="icon" href="{{ setting('favicon_logo') ? Storage::url('uploads/appLogo/app-favicon-logo.png') : '' }}"
        type="image/png">
    <link rel="stylesheet" href="{{ asset('assets/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/all.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/components.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/modules/izitoast/css/iziToast.min.css ') }}">
    <link rel="stylesheet" href="{{ asset('assets/modules/select2/dist/css/select2.min.css') }}">

</head>

<body>
    <div id="app">
        <section class="section">
            <div class="container mt-5">
                <div class="row">
                    <div
                        class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
                        <div class="login-brand">
                            <img src="{{ asset('app/uploads/appLogo/app-logo.png') }}"
                                alt="logo" class="app-logo" width="75%">
                        </div>
                        @yield('content')


                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- General JS Scripts -->

    <script src="{{ asset('js/jquery.min.js') }}"></script>
    <script src="{{ asset('assets/js/popper.min.js') }}"></script>
    <script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/js/jquery.nicescroll.min.js') }}"></script>
    <script src="{{ asset('assets/js/moment.min.js') }}"></script>
    <script src="{{ asset('assets/js/stisla.js') }}"></script>

    <script src="{{ asset('assets/js/scripts.js') }}"></script>
    <script src="{{ asset('assets/modules/izitoast/js/iziToast.min.js') }}"></script>
    <script src="{{ asset('assets/modules/select2/dist/js/select2.min.js') }}"></script>
    @include('layouts.includes.alerts')
    @stack('script')

    <!-- Page Specific JS File -->
</body>

</html>

resources/views/layouts/form.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="{{setting('rtl') == '1'?'rtl':''}}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{{ setting('favicon_logo') ? Storage::url('uploads/appLogo/app-favicon-logo.png') : '' }}" type="image/png">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ $form->title }}</title>

    <link rel="dns-prefetch" href="//fonts.gstatic.com">

    <link rel="stylesheet" href="{{ asset('assets/modules/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/modules/fontawesome/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/components.css') }}">

    <script src="{{ asset('plugins/sweetalert/js/sweetalert.min.js') }}"></script>



    <link rel="stylesheet" href="{{ asset('assets/modules/izitoast/css/iziToast.min.css ') }}">

    @stack('style')

</head>

<body>
    <div id="app">
        <div class="main-wrapper ">

            @yield('content')


        </div>
    </div>

    <script src="{{ asset('js/jquery.min.js') }}"></script>
    <script src="{{ asset('assets/modules/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/js/stisla.js') }}"></script>

    <!-- JS Libraies -->
    <script src="{{ asset('assets/modules/izitoast/js/iziToast.min.js') }}"></script>
    <script src="{{ asset('assets/modules/ckeditor/ckeditor.js') }}"></script>

    @include('layouts.includes.alerts')
    @stack('script')


</body>

</html>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="{{ setting('rtl') == '1' ? 'rtl' : '' }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Form Builder') }}</title>
    <link rel="icon" href="{{ setting('favicon_logo') ? Storage::url('uploads/appLogo/app-favicon-logo.png') : '' }}"
        type="image/png">

    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link rel="stylesheet" href="{{ asset('assets/modules/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/modules/fontawesome/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/modules/bootstrap-social/bootstrap-social.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
    @if (setting('rtl') == 'on')
        <link rel="stylesheet" href="{{ asset('assets/css/bootstrap-rtl.css') }}">
    @endif
    <link rel="stylesheet" href="{{ asset('assets/css/components.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/modules/jqvmap/dist/jqvmap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/croppie/css/croppie.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/datepicker/css/bootstrap-datepicker.standalone.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/datatable/css/datatables.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/summernote/dist/summernote-bs4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/modules/izitoast/css/iziToast.min.css ') }}">
    <link rel="stylesheet" href="{{ asset('assets/modules/select2/dist/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/jquery-confirm.min.css') }}">
    @stack('style')
</head>

<body>
    <div id="app">
        <div class="main-wrapper main-wrapper-1">
            <div class="navbar-bg"></div>
            @include('include.header')
            @include('layouts.sidebar')
            @yield('content')
            <footer class="main-footer">
                <div class="footer-left">
                    &copy; {{ date('Y') }} <a href="#" class="font-weight-bold ml-1"
                        target="_blank">{{ config('app.name') }}</a>
                </div>
                <div class="footer-right"></div>
            </footer>
            <div class="modal fade" role="dialog" id="common_modal">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title"></h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{ asset('js/jquery.min.js') }}"></script>
    <script src="{{ asset('js/tag.js') }}"></script>
    <script src="{{ asset('assets/modules/tooltip.js') }}"></script>
    <script src="{{ asset('assets/modules/popper.js') }}"></script>
    <script src="{{ asset('assets/modules/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/modules/nicescroll/jquery.nicescroll.min.js') }}"></script>
    <script src="{{ asset('assets/modules/moment.min.js') }}"></script>
    <script src="{{ asset('assets/js/stisla.js') }}"></script>
    <script src="{{ asset('assets/modules/jquery.sparkline.min.js') }}"></script>
    <script src="{{ asset('assets/modules/chart.min.js') }}"></script>
    <script src="{{ asset('plugins/summernote/dist/summernote-bs4.min.js') }}"></script>
    <script src="{{ asset('assets/modules/chocolat/dist/js/jquery.chocolat.min.js') }}"></script>
    <script src="{{ asset('assets/modules/jquery-ui/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('assets/modules/izitoast/js/iziToast.min.js') }}"></script>
    <script src="{{ asset('plugins/croppie/js/croppie.min.js') }}"></script>
    <script src="{{ asset('plugins/datepicker/js/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset('plugins/datatable/js/datatables.min.js') }}"></script>
    <script src="{{ asset('assets/modules/select2/dist/js/select2.min.js') }}"></script>
    <script src="{{ asset('assets/js/jquery-confirm.min.js') }}"></script>
    <script src="{{ asset('assets/js/scripts.js') }}"></script>
    <script src="{{ asset('plugins/sweetalert/js/sweetalert.min.js') }}"></script>
    <script src="{{ asset('assets/modules/ckeditor/ckeditor.js') }}"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    @if (!empty(setting('gtag')))

        <script async src="https://www.googletagmanager.com/gtag/js?id={{ setting('gtag') }}"></script>
        <script>
            window.dataLayer = window.dataLayer || [];

            function gtag() {
                dataLayer.push(arguments);
            }
            gtag('js', new Date());
            gtag('config', '{{ setting('gtag') }}');
        </script>
    @endif
    @include('layouts.includes.alerts')
    @stack('script')
</body>

</html>

resources/views/layouts/sidebar.blade.php
@php
use App\Models\Utility;
use App\Models\Form;
$users = \Auth::user();
$currantLang = $users->currentLanguage();
$languages = Utility::languages();
$forms = Form::all();
// $profile = asset(Storage::url('uploads/avatar/'));
@endphp
<div class="main-sidebar ">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            @if (setting('app_logo'))
            
                <img src="{{ asset('app/uploads/appLogo/app-logo.png') }}"
                    alt="logo" class="app-logo" width="75%">
                    <!-- <img src="{{ Storage::url(setting('app_logo')) ? Storage::url('uploads/appLogo/app-logo.png') : '' }}"
                    alt="logo" class="app-logo" width="60px"> -->
            @else
                <a href="{{ route('home') }}">{{ config('app.name') }}</a>
            @endif
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            @if (setting('app_small_logo'))
                <img src="{{ asset('app/uploads/appLogo/app-small-logo.png') }}"
                    alt="logo" height="30px" width="30px">
            @else
                <a href="{{ route('home') }}">{{ __('PL') }}</a>
            @endif
        </div>
        <ul class="sidebar-menu">
            <li class="nav-item">
                <a class="nav-link" href="{{ route('home') }}">
                    <i class="fas fa-fire text-primary"></i>
                    <span class="nav-link-text">{{ __('Dashboard') }}</span>
                </a>
            </li>
            
            @can('manage-role')
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('roles.index') }}">
                        <i class="fas fa-key text-primary"></i>
                        <span class="nav-link-text">{{ __('Roles') }}</span>
                    </a>
                </li>
            @endcan
            @can('manage-user')
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('users.index') }}">
                        <i class="fas fa-users text-primary"></i>
                        <span class="nav-link-text">{{ __('Users') }}</span>
                    </a>
                </li>
                @endcan
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('employees.index') }}">
                        <i class="fas fa-users text-primary"></i>
                        <span class="nav-link-text">{{ __('Employee Management') }}</span>
                    </a>
                </li>
        
          
               
           
            <!-- @can('manage-setting')
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('settings') }}">
                        <i class="fas fa-cog text-primary"></i>
                        <span class="nav-link-text">{{ __('Application Settings') }}</span>
                    </a>
                </li>
            @endcan -->
            @can('manage-form')
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('forms.index') }}">
                        <i class="fas fa-book text-primary"></i>
                        <span class="nav-link-text">{{ __('Forms') }}</span>
                    </a>
                </li>
            @endcan
            @can('manage-submitted-form')
                <li class="nav-item dropdown  ">
                    <a class="nav-link  has-dropdown" href="#">
                        <i class="fas fa-list text-primary"></i>
                        <span class="nav-link-text">{{ __('Submitted Forms') }}</span>
                    </a>
                    <ul class="dropdown-menu {{   (Request::route()->getName() == 'view.form.values') ? 'd-block' : '' }}">
                        @foreach ($forms as $form)
                            <li><a class="nav-link {{   (Request::route()->getName() == 'view.form.values') ? 'show' : '' }}" href="{{ route('view.form.values', $form->id) }}">{{ $form->title }}</a></li>
                        @endforeach
                    </ul>
                </li>
            @endcan

            @can('manage-chat')
                @if (setting('pusher_status') == '1')
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('chat') }}">
                            <i class="fas fa-comments text-primary"></i>
                            <span class="nav-link-text">{{ __('Chat') }}</span>
                        </a>
                    </li>
                @endif
            @endcan
            <!-- @can('manage-language')
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('manage.language', [$currantLang]) }}">
                        <i class="fas fa-globe text-primary"></i>
                        <span class="nav-link-text">{{ __('Manage Language') }}</span>
                    </a>
                </li>
            @endcan -->

        </ul>
    </aside>
</div>